CREATE TABLE Tools (ToolID INTEGER NOT NULL AUTO_INCREMENT, Name VARCHAR(40) NOT NULL, Logo VARCHAR(40) NULL, Description Text NULL, 
	SourceCode VARCHAR(100) NULL, PubMedID INTEGER NULL, SpecialReq Text NULL, VersionNumber VARCHAR(40), VersionDate VARCHAR(100), 
	PreviousVersion INTEGER NULL, NextVersion INTEGER NULL, License VARCHAR(100), Source VARCHAR(100) NOT NULL, 
	PRIMARY KEY (ToolID));
CREATE TABLE Links (ToolID INTEGER NOT NULL, LinkDescription VARCHAR(100) NOT NULL, LinkUrl VARCHAR(100) NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID));
CREATE TABLE Types (TypeID INTEGER NOT NULL, Type VARCHAR(100) NOT NULL, PRIMARY KEY(TypeID));
CREATE TABLE Authors (ToolID INTEGER NOT NULL, Author VARCHAR(100), FOREIGN KEY(ToolID) REFERENCES Tools(ToolID));
CREATE TABLE ToolAuthors (ToolID INTEGER NOT NULL, Author VARCHAR(75) NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID));
CREATE TABLE Institutes (ToolID INTEGER NOT NULL, Institution VARCHAR(100) NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID));
CREATE TABLE Fundings (ToolID INTEGER NOT NULL, Funding VARCHAR(100) NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID));
CREATE TABLE BiologicalDomains(DomainID INTEGER NOT NULL, Type VARCHAR(100) NOT NULL, PRIMARY KEY(DomainID));
CREATE TABLE ToolDomains(ToolID INTEGER NOT NULL, DomainID INTEGER NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID), FOREIGN KEY(DomainID) REFERENCES BiologicalDomains(DomainID));
CREATE TABLE Platforms (PlatformID INTEGER NOT NULL, Platform VARCHAR(100) NOT NULL, PRIMARY KEY(PlatformID));
CREATE TABLE PlatformType (ToolID INTEGER NOT NULL, PlatformID INTEGER NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID), FOREIGN KEY(PlatformID) REFERENCES Platforms(PlatformID));
CREATE TABLE UpstreamTools (ToolID INTEGER NOT NULL, UpstreamToolID INTEGER NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID), FOREIGN KEY(UpstreamToolID) REFERENCES Tools(ToolID));
CREATE TABLE Extends (ToolID INTEGER NOT NULL, ExtendedToolID INTEGER NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID), FOREIGN KEY(ExtendedToolID) REFERENCES Tools(ToolID));
CREATE TABLE FileTypes (FileID INTEGER NOT NULL, Type VARCHAR(100) NOT NULL, Description VARCHAR(100), PRIMARY KEY(FileID));
CREATE TABLE ToolInputs (ToolID INTEGER NOT NULL, FileID INTEGER NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID), FOREIGN KEY(FileID) REFERENCES FileTypes(FileID));
CREATE TABLE ToolOutputs (ToolID INTEGER NOT NULL, FileID INTEGER NOT NULL, FOREIGN KEY(ToolID) REFERENCES Tools(ToolID), FOREIGN KEY(FileID) REFERENCES FileTypes(FileID));
CREATE TABLE Dependencies(ToolID INTEGER NOT NULL, Dependency VARCHAR(100), FOREIGN KEY(ToolID) REFERENCES Tools(ToolID));
CREATE TABLE Tags(ToolID INTEGER NOT NULL, Tag VARCHAR(100), FOREIGN KEY(ToolID) REFERENCES Tools(ToolID));
CREATE TABLE Maintainers(ToolID INTEGER NOT NULL, Maintainer VARCHAR(100), FOREIGN KEY(ToolID) REFERENCES Tools(ToolID));