#!/bin/bash

LNAM=$(logname)

cd ~

apt-get -y update

apt-get -y install git

git clone https://juwood03:rmdepl0y@github.com/juwood03/BD2K.git

chmod -R 7777 *

cd BD2K/scripts/batch

source mysql_install

cd ~

chmod -R 7777 *

apt-get -y install nodejs

apt-get -y install npm

chmod -R 7777 *

chown -R $LNAM *

cd BD2K/web

npm install

cd ~

chmod -R 7777 *

chown -R $LNAM *

cd BD2K/scripts/batch

source install_neo4j

cd ~

chmod -R 7777 *

chown -R $LNAM *

cd BD2K/scripts/batch

source install_solr

cd ~

chmod -R 7777 *

chown -R $LNAM *

ln -s /usr/bin/nodejs /usr/bin/node

cd BD2K/web

node_modules/forever/bin/forever start server.js