#!/bin/bash

LNAM=$(logname)

cd ~

chmod -R 7777 *

cd Aztec-Web/scripts/bash

cd ~

chmod -R 7777 *

apt-get -y install nodejs

apt-get -y install npm

chmod -R 7777 *

chown -R $LNAM *

cd Aztec-Web/web

npm install

cd ~

chmod -R 7777 *

chown -R $LNAM *

cd Aztec-Web/scripts/bash

source install_neo4j

cd ~

chmod -R 7777 *

chown -R $LNAM *

cd Aztec-Web/scripts/bash

source install_solr

cd ~

chmod -R 7777 *

chown -R $LNAM *

cd Aztec-Web/scripts/bash

source install_graphviz

cd ~

chmod -R 7777 *

chown -R $LNAM *

cd Aztec-Web/scripts/bash

source install_mongodb

cd ~

chmod -R 7777 *

chown -R $LNAM *

ln -s /usr/bin/nodejs /usr/bin/node

cd Aztec-Web/web

node_modules/forever/bin/forever start server.js