#!/bin/bash

cd  ~

cd Aztec-Web/resources/after-npm

cp graph.js ~/Aztec-Web/web/node_modules/graphviz/lib/deps/graph.js

cd ~

apt-add-repository ppa:dperry/ppa-graphviz-test
apt-get update
apt-get autoremove graphviz
apt-get -y install graphviz