#!/bin/bash

apt-get remove -y --purge mysql-server mysql-client mysql-common

apt-get autoremove -y

apt-get autoclean -y

debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'

debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'

apt-get install -y mysql-server

cd ~/BD2K/scripts/sql

mysql --user=root --password=root < create.sql