#!/bin/bash

sudo apt-get update
sudo apt-get install tomcat7
sudo apt-get install tomcat7-docs tomcat7-admin tomcat7-examples
sudo apt-get install default-jdk
sudo apt-get install ant git

if ! grep -Fxq 'export JAVA_HOME=/usr/lib/jvm/default-java/' ~/.bashrc ; then 
   echo here	
   printf '%s\n' 'export JAVA_HOME=/usr/lib/jvm/default-java/' >> ~/.bashrc
   source ~/.bashrc
fi

if ! grep -Fxq 'export CATALINA_HOME=/usr/share/tomcat7/' ~/.bashrc ; then 
   printf '%s\n' 'export CATALINA_HOME=/usr/share/tomcat7/' >> ~/.bashrc
   source ~/.bashrc
fi

if ! grep -Fxq 'export CATALINA_BASE=/var/lib/tomcat7/' ~/.bashrc ; then 
   printf '%s\n' 'export CATALINA_BASE=/var/lib/tomcat7/' >> ~/.bashrc
   source ~/.bashrc
fi


